apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment
  namespace: bankapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          securityContext:
            allowPrivilegeEscalation: false
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bankapp-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankapp-secrets
                  key: MYSQL_ROOT_PASSWORD

          resources:
            requests:
              memory: "256Mi"      # mi means mb, mi in k8s
              cpu: "250m"          # m (meghabytes in cpu)
            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
