kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: bankapp
  labels:
    app: mysql

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
