kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: opaque

data:
  MYSQL_ROOT_PASSWORD: cm9vdA==                 # base64 encode of "root"
  MYSQL_PASSWORD: cm9vdA==                      # base64 encode of "root"
