kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: opaque

data:
  MYSQL_USER: cm9vdA==                          # base64 encode of "root"
  MYSQL_ROOT_PASSWORD: dGVzdEAxMjM=             # base64 encode of "test@123"
  MYSQL_PASSWORD: dGVzdEAxMjM=                  # base64 encode of "test@123"
