kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: opaque

data:
  MYSQL_USER: cm9vdA==                          # base64 encode of "root"
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=             # base64 encode of "Test@123"
  MYSQL_PASSWORD: VGVzdEAxMjM=                  # base64 encode of "Test@123"
